name: Create Release

on: 
  pull_request:
    types: [ closed ]
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  git_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 0.0.1
        release_name: Release V0.0.1
        draft: false
        prerelease: false